name: server
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-main
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - podman
      - podman-compose
  - type: systemd
    enabled:
      - sshd.service

  - type: signing